name: spring-boot3-template
services:
  redis:
    image: redis:8.2.1
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: mysql:8.0.42
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
volumes:
  redis_data:
  mysql_data:
