name: spring-boot3-template
services:
  redis:
    image: redis:8.2.1
    restart: "no"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      TZ: Asia/Shanghai
  mysql:
    image: mysql:8.0.42
    restart: "no"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend
  minio:
    image: minio/minio:RELEASE.2024-08-03T04-33-23Z.fips
    restart: "no"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      TZ: Asia/Shanghai
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio-pwd
    command: server /data --console-address ":9000" --address ":9090"
    volumes:
      - minio_data:/data
volumes:
  redis_data:
  mysql_data:
  minio_data:
