server:
  port: 8080
logging:
  level:
    root: info
    web: debug
spring:
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy://localhost:3306/backend
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/backend
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/backend
    user: root
    password: root
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
decorator:
  datasource:
    p6spy:
      log-format: "\ntime: %(executionTime) || sql: %(sql)\n"
dromara:
  x-file-storage:
    default-platform: minio-1
    thumbnail-suffix: ".min.jpg"
    minio:
      - platform: minio-1
        enable-storage: true
        access-key: XNKXOHIYjzG9Ef7JGzjC
        secret-key: WKvXFyPuAMGmPtSpiu6Y2XFLg3bpEmwK6pIhKyMV
        end-point: http://127.0.0.1:9090/
        bucket-name: spring-boot3-template
        domain: http://127.0.0.1:9090/spring-boot3-template
        base-path: /
